# Generated by Django 2.2.3 on 2022-03-25 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortafolioApp2', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portafolio',
            name='contenido',
        ),
        migrations.AlterField(
            model_name='portafolio',
            name='imagen',
            field=models.ImageField(upload_to='Portafolio'),
        ),
    ]
