# Generated by Django 2.2.3 on 2022-04-18 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PortafolioApp2', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portafolio',
            name='link',
        ),
    ]
